version: '3.8'

services:
  voting-app:
    build: .
    ports:
      - "80:80"
    environment:
      REDIS: redis
      REDIS_PWD: mysecretpassword
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "redis:latest"
    command: ["redis-server", "--requirepass", "mysecretpassword"]
    restart: always
