---
- name: Provision Python
  hosts: all
  gather_facts: false
  tasks:

    - name: Bootstrap Python
      raw: test -e /usr/bin/python3 || (export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y python3 python3-pip)

- name: Install dependencies and deploy app
  hosts: all
  gather_facts: true
  vars:
    pip_packages: ["redis", "flask", "requests"]

  roles:
    - role: ./deps/
      vars:
        pip_packages: ["redis", "flask", "requests"]

  tasks:

    - name: Copy source code to container
      copy:
        src: "./azure-vote"
        dest: "/app"

    - name: Install dependencies
      pip:
        name: "{{ pip_packages }}"
        state: present
